module.exports = [
  '/law, govt and politics/law enforcement/police',
  '/law, govt and politics/government',
  '/business and industrial',
  '/news',
  '/sports/football',
  '/sports',
  '/art and entertainment/movies and tv/movies',
  '/society/unrest and war',
  '/education/school',
  '/family and parenting/children',
  '/law, govt and politics',
  '/law, govt and politics/legal issues/human rights',
  '/law, govt and politics/politics/elections',
  '/sports/baseball',
  '/technology and computing',
  '/sports/basketball',
  '/society/crime/personal offense/homicide',
  '/law, govt and politics/legal issues/legislation',
  '/finance/investing/stocks',
  '/health and fitness',
  '/art and entertainment/movies and tv/television',
  '/science/weather',
  '/art and entertainment/music',
  '/travel/tourist facilities/hotel',
  '/society/welfare/healthcare/hospital',
  '/education/graduate school/college',
  '/technology and computing/internet technology/social network',
  '/travel/transports/air travel/airlines',
  '/business and industrial/business news',
  '/food and drink',
  '/art and entertainment/radio',
  '/law, govt and politics/government/parliament',
  '/travel/tourist destinations/france',
  '/law, govt and politics/armed forces/army',
  '/business and industrial/energy/oil',
  '/art and entertainment/books and literature',
  '/art and entertainment/humor',
  '/food and drink/food/baked goods',
  '/travel/tourist destinations/mexico and central america',
  '/travel/tourist destinations/australia and new zealand',
  '/law, govt and politics/government/courts and judiciary',
  '/business and industrial/company/annual report',
  '/family and parenting',
  '/health and fitness/disease',
  '/travel/tourist destinations/japan',
  '/art and entertainment/shows and events/concert',
  '/home and garden',
  '/technology and computing/internet technology/web search',
  '/art and entertainment/shows and events/festival',
  '/art and entertainment/radio/podcasts',
  '/science/social science/history',
  '/automotive and vehicles/cars',
  '/travel/transports/air travel/airports',
  '/religion and spirituality/islam',
  '/sports/soccer',
  '/law, govt and politics/law enforcement/fire department',
  '/sports/hockey',
  '/art and entertainment',
  '/society/work/unemployment',
  '/travel/tourist destinations/canada',
  '/society/crime',
  '/law, govt and politics/legal issues/civil law/copyright',
  '/society/sex',
  '/science/medicine/surgery',
  '/law, govt and politics/politics',
  '/business and industrial/company/merger and acquisition',
  '/art and entertainment/visual art and design/design',
  '/sports/running and jogging',
  '/technology and computing/computer certification',
  '/technology and computing/software/databases',
  '/technology and computing/consumer electronics/telephones/mobile phones/smart phones',
  '/education/high school',
  '/real estate',
  '/art and entertainment/movies and tv/reality',
  '/technology and computing/software',
  '/religion and spirituality/christianity/catholicism',
  '/business and industrial/energy/oil/oil and gas prices',
  '/business and industrial/construction',
  '/pets/dogs',
  '/travel/tourist destinations/national parks',
  '/education',
  '/finance/personal finance/insurance/life insurance',
  '/travel/tourist destinations/africa',
  '/law, govt and politics/government/legislative',
  '/business and industrial/advertising and marketing/advertising',
  '/health and fitness/disease/cancer',
  '/sports/golf',
  '/technology and computing/programming languages/javascript',
  '/business and industrial/business operations/business plans',
  '/finance/personal finance/lending/credit cards',
  '/technology and computing/consumer electronics/telephones/mobile phones',
  '/art and entertainment/movies/film festivals and awards',
  '/law, govt and politics/politics/elections/presidential elections',
  '/technology and computing/hardware/computer',
  '/society',
  '/law, govt and politics/immigration',
  '/law, govt and politics/law enforcement',
  '/style and fashion/footwear/shoes',
  '/law, govt and politics/law enforcement/highway patrol',
  '/food and drink/beverages/alcoholic beverages/cocktails and beer'
];
